apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tkjode/homelab.git
    path: base/builds/regulus/argocd/projects/monitoring/manifests/prometheus
    targetRevision: HEAD
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
