apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
	- ClusterRole-prometheus-k8s.yaml
	- ClusterRoleBinding-prometheus-k8s.yaml
	-	ConfigMap-prometheus.yaml
	- Deployment-prometheus.yaml
	- ServiceAccount-prometheus.yaml
	- Service-prometheus.yaml