apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-nzbget-tvshows
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: sonarr-nzbget-tvshows
