apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-tvshows
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: sonarr-tvshows