apiVersion: v1
kind: PersistentVolume
metadata:
  name: devpod
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-
  volumeMode: Filesystem