apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-mcp-server
  namespace: argocd
spec:
  project: inference
  sources:
  - chart: kubernetes-mcp-server
    repoURL: oci://ghcr.io/containers/charts/kubernetes-mcp-server
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/base/builds/regulus/argocd/projects/inference/manifests/kubernetes-mcp-server/values.yaml
  - repoURL: ssh://git@github.com/tkjode/homelab
    targetRevision: HEAD
    ref: values
  destination:
    namespace: kubernetes-mcp-server
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: false