apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    ingress: false
    traefik: false
    gateway: true
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - HomeLab:
            - abbr: HL
              href: https://github.com/tkjode/homelab
  services.yaml: |
    - Home Theatre:
        - Plex:
            href: https://plex.apps.phalnet.com/
            description: Enjoy movies, television and anime
        - nzbget:
            href: https://nzbget.apps.phalnet.com/
            description: NNTP Downloading Service for NZB Files
        - nzbhydra2:
            href: https://nzbhydra2.apps.phalnet.com/
            description: NZB Indexer Consolidation
        - sonarr:
            href: https://sonarr.apps.phalnet.com/
            description: Indexer Search for TV Series downloads
        - sonarr_anime:
            href: https://sonarr-anime.apps.phalnet.com/
            description: Indexer Search for Anime Series downloads
        - radarr:
            href: https://radarr.apps.phalnet.com/
            description: Indexer Search for Movie releases
    - Monitoring:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - Media:
        - widget:
            type: calendar
            firstDayInWeek: sunday
            view: monthly
            maxEvents: 30
            showTime: true
            timezone: America/New_York
            integrations:
                - type: sonarr
                    service_group: Media
                    service_name: Sonarr
                    baseUrl: https://sonarr.apps.phalnet.com

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Regulus"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""