apiVersion: v1
kind: Secret   # Example only, not applied!!!
metadata:
  name: pve-config
  namespace: homepage
data:
  proxmox.yaml: bmljZSB0cnkK   # Base64 encoded pve.url, pve.token, pve.secret values in YAML format 
