apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homepage
resources:
  - Deployment-homepage.yaml
  - HTTPRoute-homepage.yaml
  - ConfigMap-homepage-settings.yaml
  - RBAC-homepage.yaml
  - ServiceAccount-homepage.yaml
  - Secret-homepage-sa-token.yaml
  - Service-homepage.yaml
# External Secrets Operator required to add the PVE config file /w token+secret
# Add Secret Manually otherwise homepage will not start