services:
  hermes:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-agent
    command: gateway run
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    environment:
      OLLAMA_ENDPOINT: "http://10.0.0.15:11434/"
      DEFAULT_MODEL: "hf.co/unsloth/Qwen3.5-9B-GGUF:Q4_K_M"
      HERMES_GATEWAY_NO_SUPERVISE: "1"
      HERMES_DASHBOARD: "0"
      API_SERVER_ENABLED: "true"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_CORS_ORIGINS: "*"
    volumes:
      - hermes_config:/root/.config/hermes
      - hermes_data:/root/.local/share/hermes
      - opt_data:/opt/data
      - hermes_cache:/root/.cache/hermes
      - hermes_logs:/var/log/hermes
    ports:
      - "8642:8642"

volumes:
  opt_data:
  hermes_config:
  hermes_data:
  hermes_cache:
  hermes_logs:
