apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: radar-cors
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: radar
  cors:
    allowOrigins:
    - "http://localhost:8080"
    - "http://127.0.0.1:8080"
    - "https://*"
    allowCredentials: true
