apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: radar-cors
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: radar
  cors:
    allowOrigins:
    - "*"
    allowMethods:
    - "*"
    exposeHeaders:
    - "*"
    allowCredentials: true
