services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    container_name: ollama
    env_file:
    - path: HFTOKEN.env
      required: false
    environment:
      OLLAMA_CONTEXT_LENGTH: 196608
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_NUM_PARALLEL: 1
      OLLAMA_KV_CACHE_TYPE: q4_0
      CUDA_VISIBLE_DEVICES: GPU-b6e89fb8-c440-63f7-585a-c8c1215be84a
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
    name: ollama_data