services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    container_name: ollama
    env_file:
    - path: HFTOKEN.env
      required: false
    environment:
      OLLAMA_CONTEXT_LENGTH: 262144
      OLLAMA_KEEP_ALIVE: 300
      OLLAMA_NUM_PARALLEL: 1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
    name: ollama_data