- HomeLab:
    - Proxmox:
        icon: si-qnap.svg
        href: http://10.0.0.4:8006
        description: Hypervisor Login
    - Dell iDRAC:
        icon: mdi-link-variant.svg
        href: http://10.0.0.3/login.html
        description: Dell iDRAC Login
    - Plex:
        icon: si-rss.svg
        href: https://plex.apps.phalnet.com
        description: Plex Media Server
        container: plex
- NZB:
    - NZBGet:
        icon: si-qbittorrent.svg
        href: https://nzbget.apps.phalnet.com
        description: nzbget
        container: nzbget
        widget:
          type: nzbget
          url: https://nzbget.apps.phalnet.com
          username: tkjode
          password: phalnet
- Media:
    - Trackers:
        - TV:
            icon: si-sonarr.svg
            href: https://sonarr.apps.phalnet.com
            description: Sonarr
            container: sonarr
            widgets:
            - type: sonarr
              url: https://sonarr.apps.phalnet.com
              key: 9082bd325bd44943aa314acb3d906fb2
        - Anime:
            icon: si-sonarr.svg
            href: https://sonarr-anime.apps.phalnet.com
            description: Sonarr-Anime
            container: sonarr-anime
            widgets:
            - type: sonarr
              url: https://sonarr-anime.apps.phalnet.com
              key: a38c4e3b069541c496f248daaa13ba09
        - Movies:
            icon: si-radarr.svg
            href: https://radarr.apps.phalnet.com
            description: radarr
            container: radarr
            widget:
              type: radarr
              url: https://radarr.apps.phalnet.com
              key: 47ec1077380446aca0566151582480f0
        - Indexers:
            icon: mdi-database-search-outline.svg
            href: https://nzbhydra2.apps.phalnet.com
            description: NZBHydra2
            container: nzbhydra2
            widget:
              type: customapi
              url: https://nzbhydra2.apps.phalnet.com/ap/stats?apikey=7G1S5R23U4VHJ7RK459J5MAMTQ
    - Upcoming:
        - Upcoming:
            widget:
              type: calendar
              view: agenda
              maxEvents: 12 # optional - defaults to 10
              showTime: true # optional - show time for event happening today - defaults to false
              integrations: # optional
                - type: sonarr
                  service_group: Trackers
                  service_name: TV
                - type: sonarr
                  service_group: Trackers
                  service_name: Anime
                - type: radarr
                  service_group: Trackers
                  service_name: Movies
- Links:
    - Kinja:
        - Bearblog Dash:
            icon: mdi-teddy-bear.svg
            href: https://bearblog.dev/dashboard
        - An Archaeopteryx:
            icon: fossil.svg
            href: https://anarchaeopteryx.bearblog.dev
        - Fantasy Life i Project:
            icon: mdi-island-variant.svg
            href: https://fli-ginormosia.bearblog.dev
    - News:
        - Fusion Blogs:
           icon: si-rss.svg
           href: # Link
        - Tumblr:
           icon: si-tumblr.svg
           href: # Link
        - TPL:
           icon: mdi-book-open-variant.svg
           href: # Link
    - Tech:
        - LibraryThing:
           icon: si-librarything.svg
           href: https://www.librarything.com/home
        - Letterboxd:
           icon: si-letterboxd.svg
           href: https://letterboxd.com/
        - Amazon Vine:
           icon: si-amazon.svg
           href: # Link
    - HomeLab:
        - AO3:
           icon: si-archiveofourown.svg
           href: https://archiveofourown.org/
        - Reddit:
           icon: si-reddit.svg
           href: https://www.reddit.com
    - Media:
        - FFXIV Lodestone:
           icon: si-squareenix.svg
           href: https://na.finalfantasyxiv.com/lodestone
        - FFXIV Wiki:
           icon: mdi-gamepad-round.svg
           href: https://ffxiv.consolegameswiki.com/wiki/FF14_Wiki
        - Eorzea Collection:
           icon: mdi-mirror-variant.svg
           href: https://ffxiv.eorzeacollection.com/glamours
    - NZB:
        - Ocean Fishing:
           icon: mdi-sail-boat.svg
           href: https://ffxiv.pf-n.co/ocean-fishing