title: Regulus
description: HomeLab Media Services
color: red
background:
  brightness: 50
  opacity: 20
headerStyle: clean
language: en-CA
statusStyle: dot
layout:
  Links:
    tab: Start
    style: row
    columns: 6
    header: false
    Kinja:
      header: false
    News:
      header: false
    Tech:
      header: false
    Social:
      header: false
    EliteDangerous:
      header: false
    Comics:
      header: false
  HomeLab:
    tab: Start
    style: row
    columns: 7
  Media:
    tab: Start
    style: row
    columns: 2
    Trackers:
      header: false
    Upcoming:
      header: false
  NZB:
    tab: NZBGet
    style: row
    columns: 1