apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hometheatre
  namespace: argocd
spec:
  description: "CSI Drivers for NFS backed volumes and more"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'