apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/name: nginx
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: nginx
        image: alfg/nginx-rtmp:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 1935
          name: rtmp
          protocol: TCP
        - containerPort: 80
          name: hls
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /var/www/hls
          name: hls
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-conf
      - name: hls
        emptyDir: {}