apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 4
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: converter
      app.kubernetes.io/name: converter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: converter
        app.kubernetes.io/name: converter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - my-app
            topologyKey: "kubernetes.io/hostname"
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: converter
        image: ghcr.io/kennethwussmann/docker-ffmpeg-converter:latest
        imagePullPolicy: Always
        env:
        - name: SERVER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SOURCE_DIRECTORY_PATH
          value: /videos
        - name: DESTINATION_DIRECTORY_PATH
          value: /videos/converted
        - name: GLOB_PATTERNS
          value: '*.flv'
        - name: LOCK_ENABLED
          value: "true"
        - name: LOCK_STALE_AFTER_SECONDS
          value: "86400"
        - name: REMOVE_SOURCE_AFTER_CONVERT
          value: "true"
        - name: LOG_FORMAT
          value: text
        - name: FFMPEG_ARGS
          value: -y -fflags +genpts -i %s -crf 10 -vf "minterpolate=fps=60:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1" %s.mp4
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        volumeMounts:
        - mountPath: /videos
          name: videos
      volumes:
      - name: videos
        persistentVolumeClaim:
          claimName: pvc-nas-hls