apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-rtmp
spec:
  hostnames:
  - rtmp.phalnet.com
  - rtmp.apps.phalnet.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: rtmp-relay
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: rtmp
      port: 1935
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /