apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nas-hls
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8G
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: pv-nas-hls