apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rtmp-streaming
  namespace: argocd
spec:
  description: "OBS Stream Relay Services on tcp/1985 and others for remote viewing"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'