apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: security
  sources:
  - chart: falcosecurity/falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 8.0.2
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true