apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: linux-mirrors
  namespace: argocd
spec:
  description: "Creates Sync Jobs and configures homelab hosting endpoints for Ubuntu and Arch packages"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'