name: "talos-apply"
description: "Checkouts the Talos project and runs a standard init, plan and apply on a specific module"
runs:
  using: "composite"
  steps:
  - run: terraform init
    shell: /bin/sh
    working-directory: base/projects/talos-cluster/${{ inputs.module-path }}
  - run: terraform plan -out=/tf/talos-${{ inputs.module-path }}.tfplan
    shell: /bin/sh
    working-directory: base/projects/talos-cluster/${{ inputs.module-path }}
  - run: terraform apply -auto-approve -parallelism=1 /tf/talos-${{ inputs.module-path }}.tfplan
    shell: /bin/sh
    working-directory: base/projects/talos-cluster/${{ inputs.module-path }}
