apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-config
  namespace: homarr
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 256Mi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /srv/nas/kubepv/regulus/stateful/homarr#config
    server: 10.0.0.5
