apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config
  namespace: homarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: homarr-config
