apiVersion: batch/v1
kind: CronJob
metadata:
  name: apt-upgrade-patcher
  labels:
    jobgroup: parallel
spec:
  schedule: "00 01 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          name: apt-upgrade
          labels:
            jobgroup: parallel
        spec:
          containers:
          - name: apt
            image: busybox
            imagePullPolicy: IfNotPresent
            command: [ 'chroot', '/host', '/bin/bash', '-c' ]
            args: [ 'apt-get update && apt-get -y dist-upgrade && apt-get -y autoremove && apt-get clean' ]
            env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            securityContext:
              privileged: true
            volumeMounts:
            - name: host
              mountPath: /host
          hostPID: true
          hostIPC: true
          hostNetwork: true
          restartPolicy: OnFailure
          tolerations:
          - operator: Exists
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  jobgroup: parallel
          terminationGracePeriodSeconds: 0
          volumes:
          - name: host
            hostPath:
              path: /
              type: Directory
      parallelism: 9
  concurrencyPolicy: Allow