apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbhydra2-config
  namespace: nzbhydra2
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /srv/regulus/stateful/nzbhydra#config
    server: 10.0.0.5