#cloud-config
hostname: router-test
timezone: America/Toronto
bootcmd:
  - sysctl -w net.ipv4.ip_forward=1
write_files:
  - path: /etc/sysctl.d/99-ipv.conf
    content: |
      net.ipv4.ip_forward = 1
    owner: 'root:root'
    permissions: '0644'
users:
  - default
  - name: tkjode
    groups:
      - sudo
    shell: /bin/bash
    ssh_import_id: ['gh:tkjode']
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
  - iptables -A FORWARD -i eth0 -i eth1 -m state --state ESTABLISHED,RELATED -j ACCEPT
  - iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  - echo "done" > /tmp/cloud-config.done