apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarranime-anime
  namespace: sonarranime
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: sonarranime-anime