apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: userland
  namespace: argocd
spec:
  description: "Start resource creation for other projects"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'