apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: telemetry
  namespace: argocd
spec:
  description: "Installs metrics-server stack to allow for custom autoscaling"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'