apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: linux-mirrors
  namespace: argocd
spec:
  description: "Jobs to sync linux distribution repositories locally"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'