apiVersion: v1
kind: ConfigMap
metadata:
  name: default-location-conf
data:
  default-location.conf: |-
    server {
      listen 8080;
      server_name ubuntu-mirror.local;
    
      location / {
        root /usr/share/nginx/html;
        autoindex on
      }
    }