apiVersion: v1
kind: ConfigMap
metadata:
  name: apt-mirror-config
data:
  mirror.list: |-
    set base_path /out
    set mirror_path $base_path/mirror
    set skel_path $base_path/skel
    set var_path $base_path/var
    set _tilde 0
    set nthreads 8
    set slow_rate_protection off
    set weak_size_check 1

    set prometheus_enable on
    set prometheus_port 8000
    set prometheus_host localhost
   
    mirror_dist_upgrader http://archive.ubuntu.com/ubuntu

    deb https://mirror.csclub.uwaterloo.ca/ubuntu devel main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu devel-updates main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu devel-backports main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu devel-security main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu devel-proposed main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu resolute main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu resolute-updates main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu resolute-backports main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu resolute-security main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu questing main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu questing-updates main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu questing-backports main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu questing-security main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking-updates main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking-backports main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking-security main restricted universe multiverse