apiVersion: v1
kind: ConfigMap
metadata:
  name: apt-mirror-config
data:
  mirror.list: |-
    set base_path /out
    set mirror_path $base_path/mirror
    set skel_path $base_path/skel
    set var_path $base_path/var
    set _tilde 0
    set nthreads 8
    set slow_rate_protection off
    set weak_size_check 0

    set prometheus_enable on
    set prometheus_port 8000
    set prometheus_host 0.0.0.0

    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking-updates main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking-backports main restricted universe multiverse
    deb https://mirror.csclub.uwaterloo.ca/ubuntu stonking-security main restricted universe multiverse