apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-mirror
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: refresh-mirror
            app.kubernetes.io/instance: ubuntu-cswaterloo-mirror
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8000"
            prometheus.io/path: "/metrics"
        spec:
          containers:
          - name: apt-mirror2
            image: aptmirror/apt-mirror2:latest
            volumeMounts:
            - name: ubuntu-mirror-root
              mountPath: /out
            - name: mirror-config
              mountPath: /etc/apt/mirror.list
              subPath: mirror.list
            ports:
            - containerPort: 8000
              name: prometheus
              protocol: TCP
          volumes:
          - name: ubuntu-mirror-root
            persistentVolumeClaim:
              claimName: ubuntu-mirror-root
          - name: mirror-config
            configMap:
              name: apt-mirror-config
          restartPolicy: Never
