apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ubuntu
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-ubuntu
      app.kubernetes.io/name: nginx-ubuntu
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nginx-ubuntu
        app.kubernetes.io/name: nginx-ubuntu
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-content
        - mountPath: /etc/nginx/nginx.conf.template
          name: nginx-config
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-conf
          optional: false
      - name: web-content
        persistentVolumeClaim:
          claimName: ubuntu-mirror-root
