metadata:
  name: ubuntu-mirror
resources:
  - ConfigMap-apt-mirror-config.yaml
  - ConfigMap-default-location-conf.yaml
  - CronJob-refresh-mirror.yaml
  - Deployment-nginx-ubuntu.yaml
  - HTTPRoute-ubuntu-mirror.yaml
  - PersistentVolume-ubuntu-mirror.yaml
  - PersistentVolumeClaim-ubuntu-mirror-root.yaml
  - Service-mirror-http.yaml