apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-mirror
spec:
  storageClassName: nfs-bind
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 16Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /srv/nas/Mirrors/ubuntu/
    server: 10.0.0.5



