apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-base
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8G
  storageClassName: nfs-bind
  volumeMode: Filesystem
  volumeName: ubuntu-base