apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: open-webui
  namespace: open-webui
resources:
  - Deployment-open-webui.yaml
  - Service-open-webui.yaml
  - HTTPRoute-ai.yaml
  - PVC-open-webui.yaml
  - PV-open-webui.yaml
secretGenerator:
- name: webui-secret
  literals:
  - secret-key=f042f23f055bd8fc66a795727a642026af3340f042f9bd72de97063ccb230365
  - admin-default-password=changeme
configMapGenerator:
 - name: open-webui-envvars
   literals:
    - WEBUI_URL=https://ai.apps.phalnet.com
    - ENABLE_SIGNUP=True
    - ENABLE_SIGNUP_PASSWORD_CONFIRMATION=True
    - WEBUI_ADMIN_EMAIL=tkjode@gmail.com
    - WEBUI_ADMIN_NAME=Jody Reid
    - DEFAULT_MODELS=gemma4:12b
    - DEFAULT_PINNED_MODELS=gemma4:12b
    - DEFAULT_USER_ROLE=user
    - THREAD_POOL_SIZE=2000
    - ENV=prod
    - WEBUI_NAME=HomeLab AI
    - DOCKER=True
    - ENABLE_TITLE_GENERATION=True
    - LOG_FORMAT=json
    - ENABLE_AUDIT_STDOUT=True
    - AUDIT_LOG_LEVEL=METADATA
    - ENABLE_OPENAI_API=False
    - ENABLE_FOLLOW_UP_GENERATION=False
    - ENABLE_CODE_EXECUTION=False
    - ENABLE_EVALUATION_ARENA_MODELS=False
    - ENABLE_BASE_MODELS_CACHE=True
    - MODELS_CACHE_TTL=30
    - OPENAI_BASE_URL=""
    - AUDIO_TTS_ENGINE=openai
    - AUDIO_TTS_VOICE=bf_lily
    - AUDIO_TTS_OPENAI_API_BASE_URL=http://10.0.0.15:8880/v1
    - OLLAMA_BASE_URL=http://10.0.0.15:11434