apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/component: webui-storage
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
spec:
  storageClassName: iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
