## 0-tf-decom.yaml
## A re-usable Speculative Destruction Plan and Auto-Destruct
## Requires "folder" variable, sparse checkouts it from /base/builds/ and points TF at it
## S3 State may be verified for accuracy, and will evaluate the data in /build as well to determine removals.

env:
  AWS_REGION: "ca-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PROXMOX_VE_API_TOKEN: ${{ vars.PROXMOX_API_ROOT }}=${{ secrets.PROXMOX_API_ROOT_SECRET }}
  PROXMOX_VE_ENDPOINT: ${{ vars.PROXMOX_VE_ENDPOINT }}
  PROXMOX_VE_SSH_USERNAME: ${{ secrets.PROXMOX_SSH_USERNAME }}
  PROXMOX_VE_SSH_PASSWORD: ${{ secrets.PROXMOX_SSH_PASSWORD }}
  PROXMOX_VE_INSECURE: true
  TF_INPUT: 0
  TF_DATA_DIR: "/tf"
  TF_IN_AUTOMATION: "true"
  TF_VAR_proxmox_endpoint_uri: ${{ vars.PROXMOX_VE_ENDPOINT }}
  TF_VAR_target_proxmox_node_name: ${{ vars.PROXMOX_NODE }}
  TF_VAR_target_proxmox_node_ipaddr: ${{ vars.PROXMOX_NODE_IPADDR }}
  TF_VAR_iso_datastore: ${{ vars.ISO_DATASTORE }}
  TF_VAR_proxmox_node: ${{ vars.PROXMOX_NODE }}
  TF_VAR_default_ssh_pub_key: ${{ secrets.DEFAULT_PUB_KEY }}
  TF_VAR_argocd-ssh-private-key: ${{ secrets.ARGOCD_REGULUS_SSH_PRIVATE_KEY }}
  TF_VAR_repository-url: ssh://git@github.com/${{ github.repository }}


on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  terraform-plan-and-destroy:
    name: Speculative Plan and Destroy
    if: contains(github.ref, format('decom/{0}', inputs.folder) )
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
      volumes:
        - ${{ inputs.folder }}:/tf
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ./.github
            base/builds/${{ inputs.folder }}
      - run: terraform init
        shell: sh
        working-directory: base/builds/${{ inputs.folder }}
      - run: terraform plan -destroy -out=/tf/homelab-router.tfplan
        shell: sh
        working-directory: base/builds/${{ inputs.folder }}
      - run: terraform apply -destroy -auto-approve --parallelism=1
        shell: sh
        working-directory: base/builds/${{ inputs.folder }}