on:
  workflow_call:
    inputs:
      basefolder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  validate-yaml:
    name: YAML Validation
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v6
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v5
        with:
          base_dir: ${{ inputs.basefolder }}
