name: cloud-init-lab
run-name: Test Cloud-Init Support
env:
  AWS_REGION: "ca-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PROXMOX_VE_API_TOKEN: ${{ vars.PM_API_TOKEN_ID }}=${{ secrets.PM_API_TOKEN_SECRET }}
  PROXMOX_VE_ENDPOINT: ${{ vars.PROXMOX_VE_ENDPOINT }}
  PROXMOX_VE_SSH_USERNAME: ${{ secrets.PROXMOX_SSH_USERNAME }}
  PROXMOX_VE_SSH_PASSWORD: ${{ secrets.PROXMOX_SSH_PASSWORD }}
  PROXMOX_VE_INSECURE: true
  TF_INPUT: 0
  TF_DATA_DIR: "/tf"
  TF_IN_AUTOMATION: "true"
  TF_VAR_proxmox_endpoint_uri: ${{ vars.PROXMOX_VE_ENDPOINT }}
  TF_VAR_target_proxmox_node_name: ${{ vars.PROXMOX_NODE }}
  TF_VAR_target_proxmox_node_ipaddr: ${{ vars.PROXMOX_NODE_IPADDR }}
  TF_VAR_iso_datastore: ${{ vars.ISO_DATASTORE }}
  TF_VAR_proxmox_node: ${{ vars.PROXMOX_NODE }}
on:
  workflow_dispatch:
  push:
    branches: [ "feat/cloud-init" ]
    paths:
    - 'base/projects/cloud-init-testing/**'
    - '.github/workflows/cloud-init-lab.yml'
jobs:
  run-lab-steps:
    strategy:
      max-parallel: 1
      matrix:
        lab:
          - tf-ubuntu-cloud-server
    name: "Run Cloud Init Terraform"
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
      volumes:
        - ${{ matrix.lab }}:/tf
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./.github
            base/projects/cloud-init-testing/${{ matrix.lab }}
      - run: terraform init
        shell: sh
        working-directory: base/projects/cloud-init-testing/${{ matrix.lab }}
      - run: terraform plan -out=/tf/${{ matrix.lab }}.tfplan
        shell: sh
        working-directory: base/projects/cloud-init-testing/${{ matrix.lab }}
      - run: terraform apply -auto-approve -parallelism=1 /tf/${{ matrix.lab }}.tfplan
        shell: sh
        working-directory: base/projects/cloud-init-testing/${{ matrix.lab }}