name: decom-with-terraform

on:
  workflow_dispatch:
  push:
    branches: [ "main", "decom/**" ]
    paths:
      - 'base/builds/**'
      - '.github/workflows/lab-decom.yaml'
jobs:
  tf-plan-and-destroy:
    strategy:
      matrix:
        folder: [gamededi, homelab-router, nas, regulus]
    uses: ./.github/workflows/0-tf-decom.yaml
    secrets: inherit
    with:
      folder: ${{ matrix.folder }}