name: build-with-terraform

on:
  workflow_dispatch:
  push:
    branches: [ "build/**" ]
    paths:
      - 'base/builds/**'
      - '.github/workflows/lab-build.yaml'
jobs:
  tf-plan-and-apply:
    strategy:
      matrix:
        folder: [gamededi, homelab-router, nas, regulus]
    uses: ./.github/workflows/0-tf-build.yaml
    secrets: inherit
    with:
      folder: ${{ matrix.folder }}
