name: Documentation - Markdown Linting
run-name: ${{ github.actor }} has pushed changes to documentation
on:
  push:
    paths:
      - 'doc/**'
jobs:
  markdown-lint:
    runs-on: self-hosted
    container:
      image: alpine:latest
    steps:
      - run: echo "Fake Test, listing stuff"
      - name: Acquire Repository Now
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            doc
      - run: ls -al ${{ github.workspace }}/doc
      - run: |-
          echo "Job Status: ${{ job.status }}"
