name: on-push
run-name: ${{ github.actor }} pushed to branch ${{ github.ref }} in ${{ github.repository }}
on: [push]
jobs:
  Check-Repo-Root-Structure:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: ls -al .
      - run: ls -al base
      - run: ls -al doc
      - run: ls -al hack
  Check-Bases:
    runs-on: self-hosted
    needs: Check-Repo-Root-Structure
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: ls -al base/ansible
      - run: ls -al base/container
      - run: ls -al base/kubernetes
      - run: ls -al base/proxmox
      - run: ls -al base/talos
      - run: ls -al base/terraform
      - run: ls -al base/vm
  Check-Hacks:
    runs-on: self-hosted
    needs: Check-Repo-Root-Structure
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: ls -al hack/
  Check-Docs:
    runs-on: self-hosted
    needs: Check-Repo-Root-Structure
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - run: ls -al intentionalmistakedoc