name: OpenTofu ProxMox Talos Cluster
run-name: Talos Build
on:
  push:
    # paths:
    # - 'base/talos/**'
jobs:
  opentofu-version-check:
    runs-on: self-hosted
    container:
      image: ghcr.io/opentofu:latest      
    steps:
      - name: OpenTofu Version Check
        run: (ls /.dockerenv && check FOUND dockerenv) || (echo No dockerenv)