name: OpenTofu ProxMox Talos Cluster
run-name: ${{ github.actor }} changed Talos Kubernetes Build
on:
  push:
    paths:
    - 'base/talos/tf/**'
jobs:
  opentofu-init-plan:
    runs-on: self-hosted
    environment: ypres
    container:
      image: ghcr.io/opentofu/opentofu:latest
      volumes:
        - tofustate:/tf
    env:
      TF_VAR_proxmox_endpoint_uri: ${{ vars.PM_ENDPOINT }}
      TF_VAR_proxmox_parallelism: 1
      PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
      PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
    steps:
      - name: Checkout Talos TF Content
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            base/talos/tf
      - run: cp -R base/talos/tf/* /tf
      - run: tofu -chdir=/tf init
      - run: tofu -chdir=/tf plan
