name: OpenTofu ProxMox Talos Cluster
run-name: ${{ github.actor }} changed Talos Kubernetes Build
on:
  push:
    paths:
    - 'base/talos/tf/**'
    - '.github/workflows/proxmox-talos-kubernetes.yml'
jobs:
  opentofu-init-plan:
    runs-on: self-hosted
    strategy:
      matrix:
        environment: [ ypres ]
    environment: ${{ matrix.environment }}
    container:
      image: ghcr.io/opentofu/opentofu:latest
      volumes:
        - tofustate:/tf
    env:
      TF_DATA_DIR: "/tf"
      TF_IN_AUTOMATION: "true"
      TF_WORKSPACE: ${{ matrix.environment }}
      TF_VAR_proxmox_endpoint_uri: ${{ vars.PM_ENDPOINT }}      
      TF_VAR_target_proxmox_node_name: ${{ vars.PM_NODE_NAME }}
      TF_VAR_workers: ${{ vars.TALOS_WORKERS }}
      PROXMOX_VE_API_TOKEN: ${{ secrets.PM_API_TOKEN_ID }}=${{ secrets.PM_API_TOKEN_SECRET }}
      PROXMOX_VE_INSECURE: true
    steps:
      - name: Checkout Talos TF Content
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            base/talos/tf      
      - run: tofu init -var-file=${{ matrix.environment }}.tfvars
        working-directory: base/talos/tf
      - run: tofu plan -var-file=${{ matrix.environment }}.tfvars
        working-directory: base/talos/tf
