name: OpenTofu ProxMox Talos Cluster
run-name: ${{ github.actor }} changed Talos Kubernetes Build
on:
  push:
    # paths:
    # - 'base/talos/**'
jobs:
  opentofu-version-check:
    runs-on: self-hosted
    environment: ypres
    container: 
      image: ghcr.io/opentofu/opentofu:latest
      volumes:
        - tofustate:/tf       
    env:
      TF_VAR_proxmox_endpoint_uri: ${{ vars.PM_ENDPOINT }}
      TF_VAR_proxmox_parallelism: 1
      PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}      
      PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
    steps:
      - name: Checkout Talos TF Content
        uses: actions/checkout@v4
        with:
          path: /tf
          sparse-checkout: |
            base/talos/tf
      - run: ls -alR        
      - run: tofu init
        working-directory: /tf/base/talos/tf
      - run: tofu plan
        working-directory: /tf/base/talos/tf
