name: tf-talos-cluster
run-name: Talos Cluster Infrastructure
env:
  AWS_REGION: "ca-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PROXMOX_VE_API_TOKEN: ${{ vars.PM_API_TOKEN_ID }}=${{ secrets.PM_API_TOKEN_SECRET }}
  PROXMOX_VE_ENDPOINT: ${{ vars.PROXMOX_VE_ENDPOINT }}
  PROXMOX_VE_INSECURE: true
  TF_INPUT: 0
  TF_DATA_DIR: "/tf"
  TF_IN_AUTOMATION: "true"
  TF_VAR_proxmox_endpoint_uri: ${{ vars.PM_ENDPOINT }}
  TF_VAR_target_proxmox_node_name: ${{ vars.PM_NODE_NAME }}
  TF_VAR_iso_datastore: ${{ vars.ISO_DATASTORE }}
  TF_VAR_image_datastore: ${{ vars.ISO_DATASTORE }}
  TF_VAR_proxmox_node: ${{ vars.PROXMOX_NODE }}
  TF_VAR_openwrt_release: ${{ vars.OPENWRT_RELEASE }}
  TF_VAR_talos_iso_version: ${{ vars.TALOS_ISO_VERSION }}
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'base/projects/talos-cluster/**'
    - '.github/workflows/talos-cluster-unified.yml'
jobs:
  talos-build-prep:
    strategy:
      max-parallel: 1
      matrix:
        module: ["00-iso-tf", "01-network-tf", "02-compute-pool-tf"]
    name: "Talos Early Prep"
    runs-on: self-hosted
    container:
      image: hashicorp/terraform:latest
      volumes:
        - ${{ matrix.module }}:/tf
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            base/projects/talos-cluster/${{ matrix.module }}
      - name: Terraform Steps
        with:
          module-path: ${{ matrix.module }}
        uses: ./.github/actions/talos-apply/action.yaml
