name: tethys-docker

on:
  workflow_dispatch:
  push:
    branches: [ "build/tethys/**" ]
    paths:
      - 'base/builds/tethys/docker/**'
      - '.github/workflows/tethys-docker.yml'

jobs:
  validate:
    runs-on: ['self-hosted','gpu']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Validate docker-compose YAML files
        run: |
          cd "${GITHUB_WORKSPACE}"
          find ./base/builds/tethys/docker -type f -name 'docker-compose.yaml' -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file"
            docker compose -f "$file" config > /dev/null
          done
  deploy:
    runs-on: ['self-hosted','gpu']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Update tethys in /app/docker
        run: |
          cd "${GITHUB_WORKSPACE}"
          mkdir -p /app/docker
          git archive --format=tar --output /tmp/tethys-docker.tar HEAD base/builds/tethys/docker
          tar -xf /tmp/tethys-docker.tar --strip-components=4 -C /app/docker